### ISSUE TITLE
Update doc for Rate Limiter

### ISSUE THREAD

**Issue by shychka** [RobWin/resilience4j-spring-boot-demo#1]
> // For example you want to restrict the calling rate of some method to be not higher than 10 req/ms.
RateLimiterConfig config = RateLimiterConfig.builder()

Should be
> // For example you want to restrict the calling rate of some method to be not higher than 10 req/ms.
RateLimiterConfig config = RateLimiterConfig.**custom**()

**Comment by RobWin** [comment]
Thx
