### ISSUE TITLE
Can you point me to sample integration tests for Resilience4j for circuit breaker in spring boot 1.5.6 RELEASE

### ISSUE THREAD

**Issue by ronak319** [RobWin/resilience4j-spring-boot-demo#10]

**Comment by RobWin** [comment]
Do you mean something like this?
https://github.com/resilience4j/resilience4j-deprecated/blob/master/resilience4j-spring-boot/src/test/java/io/github/resilience4j/circuitbreaker/CircuitBreakerAutoConfigurationTest.java

**Comment by ronak319** [comment]
Thanks @RobWin this helps.

**Comment by ronak319** [comment]
Another followup - However is there a way to test circuitBreaker without integration test. As integration test take so long to load up.

**Comment by RobWin** [comment]
You can use unit tests like this: https://github.com/resilience4j/resilience4j/blob/master/resilience4j-circuitbreaker/src/test/java/io/github/resilience4j/circuitbreaker/CircuitBreakerTest.java

**Comment by ronak319** [comment]
Thanks @RobWin  that does help 

in your case helloWorld service is a supplier. 

My service  accepts **an argument** and **return something** and also **throws exception.** 

Can you point me to sample where it is written in non-functional manner or functional equivalent of myService ?

**Comment by ronak319** [comment]
Hey @RobWin I wanted something like this

https://github.com/resilience4j/resilience4j/blob/e431fe064467457e449536a8628fdc5211ba02f1/resilience4j-circuitbreaker/src/test/java/io/github/resilience4j/circuitbreaker/CircuitBreakerTest.java#L416

**Comment by ronak319** [comment]
we can close this issue. Thanks you very much for your prompt replies and dedication towards this project.
