### ISSUE TITLE
BusinessBService

### ISSUE THREAD

**Issue by spandit91** [RobWin/resilience4j-spring-boot-demo#11]
.compose(CircuitBreakerOperator.of(circuitBreaker))
Getting error in this line of code in BusinessBService.java class. It says: Type mismatch: cannot convert from CircuitBreakerOperator<Object> to ObservableTransformer<? super String,? extends R>

**Comment by RobWin** [comment]
Yes, the demo is pretty outdated.
You should have a look at the Spring Boot 2 demo.

**Comment by spandit91** [comment]
Thanks! RobWin.
